server {
    listen       8080;
    server_name  localhost;

    # Important: ECS logConfiguration standard out
    access_log  /dev/stdout  main;
    error_log   /dev/stderr  warn;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Ignore favicon 404 errors
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
